apiVersion: v1
kind: Secret
metadata:
  name: edumanager-secret
  namespace: edumanager
type: Opaque
data:
  POSTGRES_PASSWORD: ZWR1bWFuYWdlcl9wYXNzd29yZA==
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmQ=
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQta2V5LWZvci1qd3QtdG9rZW4tZ2VuZXJhdGlvbi1zaG91bGQtYmUtYXQtbGVhc3QtMjU2LWJpdHM=
